### PR TITLE
Added index method

### PR DESCRIPTION
**Pull request by simonexmachina**

### CODE REVIEW

**Comment by simonexmachina** [comment]
Just realised that this method is from Cloudant, not CouchDB. Would you be interested in having this module support the extra methods from https://github.com/cloudant/nodejs-cloudant as well?

**Comment by mcrummey** [comment]
I don't think they should support Cloudant's api in this library.  I think it would be good  to stick with vanilla Nano. 

 It looks like Cloudant extended Nano.  I think you would want to extend this in the same way.  Maybe call it nodejs-cloudant-promises.  Then add the additional apis that are a part of the Cloudant service.

**Comment by simonexmachina** [comment]
Yes that's what I was thinking too. Thanks.

**Comment by mcrummey** [comment]
With Mango, it looks like these verbs will be closely associated with CouchDb 2.0.  

So maybe in the future Nano will pick them up :)

**Pull request closed without merging**
